version: '3'

services:
  insomnia-survey-api:
    build: .
    image: detmitchell/insomnia-survey-api
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/insomnia_surveys
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/insomnia-survey-api
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge